[build]
  functions = "functions"
  command = "npm run build"
  publish = "public"

[[plugins]]
  package = "netlify-plugin-gatsby-cache"

[dev]
  command = "yarn run start"
  publish = "dist"
  functions = "functions"

[[redirects]]
  from = "/product"
  to = "/"
  status = 301
